# Generated by Django 6.1.1 on 2026-09-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_listing_fulfillment_option'),
        ('marketplace', '0008_user_email_verified_at'),
    ]

    operations = [
    ]
