# Generated by Django 6.1.1 on 2026-09-23 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_watchlist_and_admin_activity_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMarketplacePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, choices=[('MEETUP', 'Arrange payment at meet-up'), ('EXTERNAL', 'External payment app')], max_length=20)),
                ('default_fulfillment', models.CharField(blank=True, choices=[('PICKUP', 'Pickup only'), ('DELIVERY', 'Local delivery available'), ('EITHER', 'Pickup or local delivery')], max_length=20)),
                ('delivery_notes', models.TextField(blank=True)),
                ('notify_inquiries', models.BooleanField(blank=True, null=True)),
                ('notify_bundles', models.BooleanField(blank=True, null=True)),
                ('notify_pricing', models.BooleanField(blank=True, null=True)),
                ('notify_moveout', models.BooleanField(blank=True, null=True)),
                ('notify_transactions', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user marketplace preferences',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5')],
            },
        ),
        migrations.CreateModel(
            name='UserMeetupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_meetup_location_name_per_user'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='one_primary_meetup_location_per_user')],
            },
        ),
    ]
