# Generated by Django 6.1.1 on 2026-09-23 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_usermarketplacepreferences_review_usermeetuplocation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='review_rating_between_1_and_5',
        ),
        migrations.RemoveField(
            model_name='usermarketplacepreferences',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='usermeetuplocation',
            name='unique_meetup_location_name_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='usermeetuplocation',
            name='one_primary_meetup_location_per_user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewed_user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='UserMarketplacePreferences',
        ),
        migrations.RemoveField(
            model_name='usermeetuplocation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='UserMeetupLocation',
        ),
    ]
