# Generated by Django 6.1.1 on 2026-09-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_listingimage'),
        ('marketplace', '0014_remove_review_review_rating_between_1_and_5_and_more'),
    ]

    operations = [
    ]
