# Generated by Django 6.1.1 on 2026-09-24 04:10

from django.db import migrations
from django.conf import settings
from django.core.files import File
from pathlib import Path


def preserve_profile_images(apps, schema_editor):
    Listing = apps.get_model("marketplace", "Listing")
    ListingImage = apps.get_model("marketplace", "ListingImage")
    database = schema_editor.connection.alias
    storage = ListingImage._meta.get_field("image").storage
    for listing in Listing.objects.using(database).exclude(image="").iterator():
        name = listing.image.name
        if not name:
            continue
        # The profile branch previously stored uploads under BASE_DIR/media.
        if not storage.exists(name):
            legacy = Path(settings.BASE_DIR) / "media" / name
            if legacy.is_file():
                with legacy.open("rb") as source:
                    name = storage.save(name, File(source))
        images = ListingImage.objects.using(database).filter(listing_id=listing.pk)
        if not images.filter(image=name).exists():
            # Keep current week3 photos first, while retaining the legacy upload.
            last = images.order_by("-position").first()
            ListingImage.objects.using(database).create(
                listing_id=listing.pk,
                uploaded_by_id=listing.seller_id,
                image=name,
                position=last.position + 1 if last else 0,
            )


def restore_profile_images(apps, schema_editor):
    Listing = apps.get_model("marketplace", "Listing")
    ListingImage = apps.get_model("marketplace", "ListingImage")
    database = schema_editor.connection.alias
    for listing in Listing.objects.using(database).all().iterator():
        image = ListingImage.objects.using(database).filter(
            listing_id=listing.pk
        ).exclude(image="").order_by("position", "pk").first()
        if image:
            Listing.objects.using(database).filter(pk=listing.pk).update(image=image.image.name)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_merge_20260923_2310'),
    ]

    operations = [
        migrations.RunPython(preserve_profile_images, restore_profile_images),
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
    ]
