# Generated by Django 6.1.1 on 2026-09-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messageimage_conversation_listing_image_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body_text',
            field=models.TextField(blank=True),
        ),
    ]
