# Generated by Django 6.1.1 on 2026-09-23 13:14

from django.db import migrations


def backfill(apps, schema_editor):
    Conversation = apps.get_model("messaging", "Conversation")
    for conversation in Conversation.objects.select_related("listing").filter(listing__isnull=False).iterator():
        listing = conversation.listing
        Conversation.objects.filter(pk=conversation.pk).update(
            listing_title_snapshot=listing.title,
            listing_price_snapshot=listing.listing_price,
            listing_image_snapshot=listing.image_url,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_body_text'),
    ]

    operations = [migrations.RunPython(backfill, migrations.RunPython.noop)]
