# Generated by Django 6.1.1 on 2026-09-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_backfill_listing_snapshots'),
        ('messaging', '0005_remove_conversation_lifecycle_statuses'),
    ]

    operations = [
    ]
