# Generated by Django 6.1.1 on 2026-09-28 01:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_consolidate_profile_images'),
        ('messaging', '0006_merge_20260923_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('awaiting_buyer', 'Awaiting buyer'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('superseded', 'Superseded'), ('confirmed', 'Confirmed'), ('unavailable', 'Unavailable')], default='awaiting_buyer', max_length=20)),
                ('client_request_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_proposals', to='messaging.conversation')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='messaging.dealproposal')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_proposal', to='marketplace.transaction')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'awaiting_buyer')), fields=('conversation',), name='one_awaiting_deal_per_conversation'), models.UniqueConstraint(fields=('conversation', 'client_request_id'), name='unique_deal_request_per_conversation'), models.CheckConstraint(condition=models.Q(('agreed_price__gte', Decimal('0.01')), ('agreed_price__lte', Decimal('999999.99'))), name='deal_price_in_range'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'confirmed'), ('transaction__isnull', False)), models.Q(models.Q(('status', 'confirmed'), _negated=True), ('transaction__isnull', True)), _connector='OR'), name='confirmed_deal_has_transaction')],
            },
        ),
    ]
