# Generated by Django 6.1.1 on 2026-09-24 20:03

import marketplace.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_merge_20260923_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='listing_image_snapshot',
            field=models.CharField(blank=True, max_length=2048, validators=[marketplace.validation.validate_image_reference]),
        ),
    ]
